# -*- coding: utf-8 -*-
"""EmilyJordanExporatoryDataProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uo-cdsGMWXzJuBsVq2-hENqqZBwzkq7_
"""

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

print("This is the data frame we will be working with, with over 26,000 participants!")
data = (pd.read_csv('EDAData.csv', error_bad_lines=False))
frame = pd.DataFrame(data)
print(frame)

fig = plt.figure(figsize = (15, 15))
plt.scatter(data["Half"], data["Official Time"])
plt.title("Official Time compared to the Halfway Point Time")
plt.xlabel("Halfway Point Time")
plt.ylabel("Final Finish Time")

fig = plt.figure(figsize = (15, 15))
plt.scatter(data["Country"], data["Official Time"])
plt.title("Official Time vs. Country")
plt.xlabel("Country")
plt.ylabel("Official Time")

fig = plt.figure(figsize = (10,10))
x = "Age"
plt.hist(frame[x], bins= 40)
plt.title("Age Histogram of Boston Marathon Runners")
plt.ylabel("Number of Runners")
plt.xlabel("Age")

fig = plt.figure(figsize = (15, 15))
plt.plot(frame["Age"], frame["Official Time"])
plt.title("Age x Official Time")
plt.ylabel("Official Time")
plt.xlabel("Age")
plt.grid(color='k', linestyle='-', linewidth=0.3)

byCountry = data.groupby("Country")["Name"].count()
byCountry.head(40000)
fig = plt.figure(figsize = (15, 15))
plt.plot(byCountry)
plt.title("Grouping participants by Country of Origin")

fig = plt.figure(figsize = (15, 15))
plt.scatter(data["5K"], data["Official Time"], c = "k")
plt.title("Official Time vs 5K Time")
plt.xlabel("5K Time")
plt.ylabel("Final Finish Time")

ages = (data["Age"])
ages = ages.sort_values()
bins = [18, 30, 40, 50, 60, 70, 120]
labels = ['18-29', '30-39', '40-49', '50-59', '60-69', '70+']
ages['agerange'] = pd.cut(ages, bins, labels = labels,include_lowest = True)
print(ages)

fig = plt.figure(figsize = (15, 15))
plt.scatter(data["Overall"], data["Age"], c = "r")

print(frame[:1])

fig = plt.figure(figsize = (15, 15))
plt.hist(data["M/F"])
plt.title("Comparing Male vs Female Participant")
plt.xlabel("Male vs Female")
labels = [5, 10, 15, 20, 25, 30, 35, 40, 45]
plt.yticks(labels, rotation ='horizontal') 
plt.grid(color='k', linestyle='-', linewidth=0.3)

fig = plt.figure(figsize= (30, 30))
#plt.scatter(data["Official Time"], data["Age"], c = "k")
#bins_list = []
plt.hist(data["Official Time"], data["Age"], c = "k")

x = uploaded('overall')
y = uploaded('bib')
fig = plt.figure()
ax = fig.add_subplot(111)
plt.show()